build:
  maxIssues: 10
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  LongMethod:
    active: true
    threshold: 40
  LargeClass:
    active: true
    threshold: 300

style:
  active: true
  MagicNumber:
    active: true
    excludes:
      - '0'
      - '1'
      - '-1'
      - '2'
      - '100'
      - '1000'
  NewLineAtEndOfFile:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true

comments:
  active: true
  CommentOverPrivateMethod:
    active: false
  CommentOverPrivateProperty:
    active: false
